/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import javax.swing.DefaultListModel;
import shop.Cart;
import shop.CartManager;
import shop.GetCartInfo;

/**
 *
 * @author thompadude
 */
public class MainWindow extends javax.swing.JFrame {

    int selectedChili;
    String nameOfChili;
    CartManager cartManager = new CartManager();
    Cart cart = cartManager.createCart();

    /**
     * Creates new form Main
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        chiliesSelectionComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        chiliInfoTextPane = new javax.swing.JTextPane();
        heatProgressBar = new javax.swing.JProgressBar();
        quitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pepperPic = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addChiliesButton = new javax.swing.JButton();
        amountOfChiliesToAdd = new javax.swing.JSpinner();
        viewCartButton = new javax.swing.JButton();
        removeChiliesButton = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chili Store");
        setBackground(new java.awt.Color(231, 149, 145));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(231, 149, 145));
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(864, 582));
        setSize(new java.awt.Dimension(864, 582));

        jPanel1.setBackground(new java.awt.Color(231, 149, 145));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 450));

        jPanel3.setBackground(new java.awt.Color(248, 51, 60));

        chiliesSelectionComboBox.setMaximumRowCount(12);
        chiliesSelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Choose a Chili Pepper", "Sweet Bell Pepper", "Pimento Chili Pepper", "Poblano Chili Pepper", "Jalapeno Pepper", "Cayenne/Tabasco Pepper", "Thai/Indian Pepper", "Jamaican Hot", "Devil's Tongue", "Ghost Pepper", "Trinidad Moruga Scorpion Chili Pepper", "Carolina Reaper" }));
        chiliesSelectionComboBox.setToolTipText("Choose a chili for more information");
        chiliesSelectionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chiliesSelectionComboBoxItemStateChanged(evt);
            }
        });

        chiliInfoTextPane.setEditable(false);
        chiliInfoTextPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 149, 145), 5));
        jScrollPane1.setViewportView(chiliInfoTextPane);

        heatProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        heatProgressBar.setForeground(new java.awt.Color(255, 255, 255));
        heatProgressBar.setToolTipText("");
        heatProgressBar.setBorderPainted(false);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 149, 145));
        jLabel1.setText("Heat Level");

        pepperPic.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 149, 145));
        jLabel3.setText("Shopping Cart");

        addChiliesButton.setText("Add");
        addChiliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChiliesButtonActionPerformed(evt);
            }
        });

        amountOfChiliesToAdd.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(100), Integer.valueOf(1)));

        viewCartButton.setText("View Cart");
        viewCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartButtonActionPerformed(evt);
            }
        });

        removeChiliesButton.setText("Remove");
        removeChiliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeChiliesButtonActionPerformed(evt);
            }
        });

        feedback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        feedback.setForeground(new java.awt.Color(231, 149, 145));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(chiliesSelectionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amountOfChiliesToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addChiliesButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeChiliesButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(viewCartButton))
                                    .addComponent(feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pepperPic, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(heatProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quitButton)))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, quitButton});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addChiliesButton, removeChiliesButton, viewCartButton});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chiliesSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pepperPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(amountOfChiliesToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addChiliesButton)
                            .addComponent(viewCartButton)
                            .addComponent(removeChiliesButton))
                        .addGap(18, 18, 18)
                        .addComponent(feedback)
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heatProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        heatProgressBar.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(248, 51, 60));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/header.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel2.add(jLabel2, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chiliesSelectionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chiliesSelectionComboBoxItemStateChanged
        selectedChili = chiliesSelectionComboBox.getSelectedIndex();

        SetChiliTextAndHeat setChiliInfo = new SetChiliTextAndHeat();
        String setText = setChiliInfo.setInfoAndHeat(selectedChili, heatProgressBar);

        SetChiliPicture spp = new SetChiliPicture();
        spp.setPepperPicture(selectedChili, pepperPic);

        chiliInfoTextPane.setText(setText);
    }//GEN-LAST:event_chiliesSelectionComboBoxItemStateChanged

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void addChiliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChiliesButtonActionPerformed
        selectedChili = chiliesSelectionComboBox.getSelectedIndex();
        Integer amountOfChiliesToBuy = (Integer) amountOfChiliesToAdd.getValue();

        cartManager.addChiliesToCart(cart, amountOfChiliesToBuy, selectedChili);

        nameOfChili = chiliesSelectionComboBox.getSelectedItem().toString();

        if (nameOfChili.contains("Please")) {
            feedback.setText("*** Please choose a chili ***");
        } else if (amountOfChiliesToBuy < 1) {
            feedback.setText("*** Please enter a positive number ***");
        } else if (!nameOfChili.contains("Please")) {
            feedback.setText(amountOfChiliesToBuy + " " + nameOfChili + " added.");
        }

        amountOfChiliesToAdd.setValue(0);
    }//GEN-LAST:event_addChiliesButtonActionPerformed

    private void viewCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartButtonActionPerformed
        CartWindow cartGraphics = new CartWindow(cart);
        cartGraphics.setVisible(true);
    }//GEN-LAST:event_viewCartButtonActionPerformed


    private void removeChiliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChiliesButtonActionPerformed
        Integer amountOfChiliesToRemove = (Integer) amountOfChiliesToAdd.getValue();
        nameOfChili = chiliesSelectionComboBox.getSelectedItem().toString();

        String feedbackText = "*** Please enter a positive number ***";

        if (!(amountOfChiliesToRemove < 1)) {
            feedbackText = cartManager.removeSelectedChiliFromCart(cart, nameOfChili, amountOfChiliesToRemove);
        }

        if (amountOfChiliesToRemove < 1) {
            feedback.setText(feedbackText);
        }

        amountOfChiliesToAdd.setValue(0);

        if (!nameOfChili.contains("Please")) {
            feedback.setText(feedbackText);
        } else {
            feedback.setText("*** Please choose a chili ***");
        }
    }//GEN-LAST:event_removeChiliesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChiliesButton;
    private javax.swing.JSpinner amountOfChiliesToAdd;
    private javax.swing.JTextPane chiliInfoTextPane;
    private javax.swing.JComboBox chiliesSelectionComboBox;
    private javax.swing.JLabel feedback;
    private javax.swing.JProgressBar heatProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pepperPic;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton removeChiliesButton;
    private javax.swing.JButton viewCartButton;
    // End of variables declaration//GEN-END:variables
}
